version: '3.8'

services:
  java:
    build:
      dockerfile: ./dockerfiles/java/Dockerfile
    container_name: webapimock_app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - node
    volumes:
      - ./application/webapimock:/webapimock
      - ./scripts/java:/webapimock/scripts
      - volume_trick:/webapimock/frontend/node_modules
    working_dir: /webapimock
    ports:
      - 8080:8080
    tty: true
  mysql:
    image: mysql:8.0.33
    container_name: webapimock_db
    volumes:
      - ./scripts/mysql:/scripts
    working_dir: /scripts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
volumes:
  volume_trick:
